version: '2'
services:
    checkers:
      build: ./
      volumes:
        - ./app/:/usr/src/app
    nginx:
      image: nginx
      volumes:
        - ./app/static:/usr/share/nginx/html:ro
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      ports:
        - 80:80

