version: '2'
services:
    # define a container called checkers
    checkers:  
      # this container is based on Dockerfile in current directory 
      build: ./ 
      # mount folder with source code
      volumes:
        - ./app/:/usr/src/app
    # define a container called nginx
    nginx:
      # use nginx image from Docker hub
      image: nginx
      # mount volumes with static files and nginx configuration
      volumes:
        - ./app/static:/usr/share/nginx/html:ro
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # expose port 80 in the container as port 80 to the outside world
      command: [nginx-debug, '-g', 'daemon off;']
      ports:
        - 80:80